### ISSUE TITLE
Have you even tested this?

### ISSUE THREAD

**Issue by icemagno** [heremaps/quantized-mesh-viewer#14]
Can't put it to run after 3 hours trying to solve many errors.

The last I can't pass thru:

```
    ERROR in ./src/map/index.js
    Module not found: Error: Can't resolve '/tilesets' in '/usr/src/app/src/map'
     @ ./src/map/index.js 2:0-39 7:28-43
```

**Comment by mykolaharmash** [comment]
Tried to run it inside a container and with just `npm start`, works in both cases. Would help if you provide some more details on how you try to run it.

**Comment by mykolaharmash** [comment]
I'm closing this for now. If you still want a followup, please create a new issue with more details.
